# Site Configuration
timezone: America/Sao_Paulo

title: Gustavo Ribeiro
description: Desenvolvedor Frontend, freelancer e fotógrafo nas horas vagas.
url: https://gustavoribeiro.com

permalink: "/:categories/:year/:month/:title.html"